import { ITweet } from "../interfaces/tweets";

const tweets: ITweet[] = [
  {
    id: "1",
    author_name: "Juanceto",
    author_tag: "juan",
    content: "Hello this is just a placeholder tweet",
    likes: 12,
    comments: 4,
    retweets: 6,
    avatar: undefined,
  },
  {
    id: "82",
    author_name: "Luceta",
    author_tag: "Luz123",
    content: "Hello guys i love this",
    likes: 1,
    comments: 14,
    retweets: 34,
    avatar: undefined,
  },
  {
    id: "72",
    author_name: "Darkses",
    author_tag: "Kda32",
    content: "Hello this is just a placeholder tweet",
    likes: 16,
    comments: 4,
    retweets: 21,
    avatar: undefined,
  },
  {
    id: "265",
    author_name: "Kiko",
    author_tag: "Kekto",
    content: "Hello this is just a placeholder tweet",
    likes: 6,
    comments: 8,
    retweets: 11,
    avatar: undefined,
  },
  {
    id: "5462",
    author_name: "Kiko",
    author_tag: "Kekto",
    content: "Hello this is just a placeholder tweet",
    likes: 6,
    comments: 8,
    retweets: 11,
    avatar: undefined,
  },
  {
    id: "265",
    author_name: "Kiko",
    author_tag: "Kekto",
    content: "Hello this is just a placeholder tweet",
    likes: 6,
    comments: 8,
    retweets: 11,
    avatar: undefined,
  },
  {
    id: "5",
    author_name: "Kiko",
    author_tag: "Kekto",
    content: "Hello this is just a placeholder tweet",
    likes: 6,
    comments: 8,
    retweets: 11,
    avatar: undefined,
  },
  {
    id: "253",
    author_name: "Kiko",
    author_tag: "Kekto",
    content: "Hello this is just a placeholder tweet",
    likes: 6,
    comments: 8,
    retweets: 11,
    avatar: undefined,
  },
  {
    id: "22",
    author_name: "Kiko",
    author_tag: "Kekto",
    content: "Hello this is just a placeholder tweet",
    likes: 6,
    comments: 8,
    retweets: 11,
    avatar: undefined,
  },
  {
    id: "33",
    author_name: "Kiko",
    author_tag: "Kekto",
    content: "Hello this is just a placeholder tweet",
    likes: 6,
    comments: 8,
    retweets: 11,
    avatar: undefined,
  },
];

export default tweets;
