const tweets = [
  {
    author_name: "Juanceto",
    author_tag: "juan",
    content: "Hello this is just a placeholder tweet",
    likes: 12,
    comments: 4,
    retweets: 6,
    avatar: undefined,
  },
  {
    author_name: "Luceta",
    author_tag: "Luz123",
    content: "Hello guys i love this",
    likes: 1,
    comments: 14,
    retweets: 34,
    avatar: undefined,
  },
  {
    author_name: "Darkses",
    author_tag: "Kda32",
    content: "Hello this is just a placeholder tweet",
    likes: 16,
    comments: 4,
    retweets: 21,
    avatar: undefined,
  },
  {
    author_name: "Kiko",
    author_tag: "Kekto",
    content: "Hello this is just a placeholder tweet",
    likes: 6,
    comments: 8,
    retweets: 11,
    avatar: undefined,
  },
  {
    author_name: "Kiko",
    author_tag: "Kekto",
    content: "Hello this is just a placeholder tweet",
    likes: 6,
    comments: 8,
    retweets: 11,
    avatar: undefined,
  },
  {
    author_name: "Kiko",
    author_tag: "Kekto",
    content: "Hello this is just a placeholder tweet",
    likes: 6,
    comments: 8,
    retweets: 11,
    avatar: undefined,
  },
  {
    author_name: "Kiko",
    author_tag: "Kekto",
    content: "Hello this is just a placeholder tweet",
    likes: 6,
    comments: 8,
    retweets: 11,
    avatar: undefined,
  },
  {
    author_name: "Kiko",
    author_tag: "Kekto",
    content: "Hello this is just a placeholder tweet",
    likes: 6,
    comments: 8,
    retweets: 11,
    avatar: undefined,
  },
  {
    author_name: "Kiko",
    author_tag: "Kekto",
    content: "Hello this is just a placeholder tweet",
    likes: 6,
    comments: 8,
    retweets: 11,
    avatar: undefined,
  },
  {
    author_name: "Kiko",
    author_tag: "Kekto",
    content: "Hello this is just a placeholder tweet",
    likes: 6,
    comments: 8,
    retweets: 11,
    avatar: undefined,
  },
];

export default tweets;
